### ISSUE TITLE
Frame size changes with h264 hw decoder using VideoToolbox

### ISSUE THREAD

**Issue by frogblueDFi** [baresip/baresip#2719]
Hi!

I am using baresip/ffmpeg/h264 decoding with VideoToolbox hardware acceleration on iOS.
If the incoming video stream changes its frame width/height, the h264 decoding stops with error log:
`avcodec: decode: Error transferring the data to system memory`
Changing the frame size occurs e.g. when the sending mobile device is rotated and video starts sending with 288x352 rather than 352x288 in landscape mode.
This works fine if libx264 software decoding is used.
Guess the VTDecompressionSession must be reconfigured or reallocated to accept the new frame size.

Any ideas on this? Maybe a fast fix?
Could a use as a workaround hw access for encoding but NOT for decoding?

Regards
Dietmar

**Comment by frogblueDFi** [comment]
Tried with both v3.2.0 (working excellent) and v3.5.1 (has issues for me) by just replacing decode.c.
Same behaviour for both versions.

iOS: I see only the typical h264 "green video" and it crashes very fast.

Stack:
`#1	0x0000000102e9e048 in vidframe_copy at /<path>/re/rem/vid/frame.c:390
#2	0x0000000102ece28c in avformat_video_copy at  /<path>/baresip/modules/avformat/video.c:117
#3	0x0000000102ecb8b0 in avformat_video_alloc ()
#4	0x0000000102ec320c in handle_rtp at  /<path>/baresip/src/stream.c:388
#5	0x0000000102ec2f54 in stream_decode at  /<path>/baresip/src/stream.c:512
#6	0x0000000102ec2c68 in rtp_handler at  /<path>/baresip/src/stream.c:475
#7	0x0000000102e5fe9c in udp_recv_handler at  /<path>/re/src/rtp/rtp.c:214
#8	0x0000000102e7476c in udp_read at  /<path>/re/src/udp/udp.c:209
#9	0x0000000102e73ddc in udp_read_handler at  /<path>/re/src/udp/udp.c:222
#10	0x0000000102e56f20 in fd_poll at  /<path>/re/src/main/main.c:802
#11	0x0000000102e5638c in re_main at  /<path>/re/src/main/main.c:976
`

macOS: Most of the time I have the typical "green video" alternating with the correct image.
Hm, anyway seems to solve the issue with frame size changes in some kind.
Also the green video rotates!


Thank you

**Comment by sreimers** [comment]
I updated the PR, I can try later if this works on my nvidia hardware test system.

**Comment by frogblueDFi** [comment]
Tried your updated PR again. With git branches re/baresip main/av_hwframe_transfer_data.
Excellent !!!
Image frame rotation (width/height switches) or complete frame size changes (CIF<->VGA<->HD) are correctly handled.
Just replacing code.c in re/baresip version v3.2.0 is also functional.
So I can keep on working with v3.2.0 until I can have a closer look on my issues with newer versions.

Thank you ver much again!!!
Dietmar

**Comment by frogblueDFi** [comment]
Ups, still an issue with an iPad 6th generation, crash when initialising decoder.
It crashes both with decode.c from baresip v3.2.0 and your PR.

Bad instruction in init_decoder when calling av_buffer_ref(avcodec_hw_device_ctx)
Any ideas?

Dietmar

**Comment by frogblueDFi** [comment]
Stepped thru, avcodec_hw_device_ctx is correctly initialised. No obvious errors.

Crash both on encoding and decoding parts:

Crash on encoding (atomic_fetch_sub_explicit)

```
#0	0x0000000101dc4b20 in buffer_replace [inlined] at /<path>/ffmpeg/libavutil/buffer.c:129
#1	0x0000000101dc4b10 in av_buffer_unref at /<path>/ffmpeg/libavutil/buffer.c:144
#2	0x0000000101dcddf8 in av_frame_unref at /<path>/ffmpeg/libavutil/frame.c:488
#3	0x00000001013f14d4 in ff_encode_encode_cb at /<path>/ffmpeg/libavcodec/encode.c:269
#4	0x00000001013f19fc in encode_simple_internal [inlined] at /<path>/ffmpeg/libavcodec/encode.c:309
#5	0x00000001013f1950 in encode_simple_receive_packet [inlined] at /<path>/ffmpeg/libavcodec/encode.c:323
#6	0x00000001013f193c in encode_receive_packet_internal at /<path>/ffmpeg/libavcodec/encode.c:357
#7	0x00000001013f17e0 in avcodec_send_frame at /<path>/ffmpeg/libavcodec/encode.c:506
#8	0x0000000101154834 in avcodec_encode at /<path>/baresip/modules/avcodec/encode.c:484
#9	0x00000001011461c8 in encode_rtp_send at /<path>/baresip/src/video.c:445
#10	0x0000000101143d60 in vidsrc_frame_handler at /<path>/baresip/src/video.c:479
#11	0x000000010115d15c in capture at /<path>/baresip/frogblue_modules/frogcapture/frogcapture.c:61
#12	0x0000000100dab41c in fbsip::BaresipInterface::setVideoProbeFrame(QVideoFrame::PixelFormat, unsigned short, unsigned short, unsigned short const*, unsigned char* const*) at /<path>/src/BaresipInterface.cpp:884

```
Crash on decoding

```
#0	0x0000000101910aec in av_buffer_ref at /<path>/ffmpeg/libavutil/buffer.c:112
#1	0x0000000100ca1ae0 in init_decoder at /<path>/baresip/modules/avcodec/decode.c:142
#2	0x0000000100ca17e4 in avcodec_decode_update at /<path>/baresip/modules/avcodec/decode.c:183
#3	0x0000000100c8f7a4 in video_decoder_set at /<path>/baresip/src/video.c:1611
#4	0x0000000100c8f22c in video_update at /<path>/baresip/src/video.c:1272
#5	0x0000000100c6f7e0 in call_update_media at /<path>/baresip/src/call.c:371
#6	0x0000000100c723b0 in update_media at /<path>/baresip/src/call.c:386
#7	0x0000000100c74a74 in sipsess_answer_handler at /<path>/baresip/src/call.c:1887
#8	0x0000000100c51bc4 in invite_resp_handler at /<path>/re/src/sipsess/connect.c:131
#9	0x0000000100c44514 in sipsess_request_alloc at /<path>/re/src/sipsess/request.c:57
#10	0x0000000100c441e0 in sipsess_request_alloc at /<path>/re/src/sipsess/request.c:75
#11	0x0000000100c3e2a4 in rtmp_amf_request ()

```
Last log entries

```
7-user12@sip.test.frogblue.cloud: Call answered: sip:7-user1@sip.test.frogblue.cloud;transport=tls
BaresipInterface.cpp::1020 - uaEventHandler ev:  UA_EVENT_CALL_ANSWERED sip:7-user1@sip.test.frogblue.cloud;transport=tls
BaresipInterface.cpp::1145 - Call answered sip:7-user1@sip.test.frogblue.cloud;transport=tls
call: update media
BaresipInterface.cpp::1020 - uaEventHandler ev:  UA_EVENT_CALL_REMOTE_SDP answer
BaresipInterface.cpp::1174 - SDP remote direction: recvonly
stream: update 'audio'
stream: receive: setting SSRC: 62f1b5f0
stream: audio: starting RTCP with remote 128.140.13.181:41827
stream: update 'video'
stream: receive: setting SSRC: 33b29e17
stream: video: starting RTCP with remote 128.140.13.181:41863
audio: update
audio: Set audio decoder: G722 16000Hz 1ch
audio: start
audio: create auplay buffer [20 - 160 ms] [640 - 5120 bytes]
2023-09-20 08:48:38.108311+0200 frogSIP[2918:1337462] handleRouteChange
2023-09-20 08:48:38.109291+0200 frogSIP[2918:1337462] Port name: Speaker Speaker
2023-09-20 08:48:38.238991+0200 frogSIP[2918:1337462] handleRouteChange
2023-09-20 08:48:38.239782+0200 frogSIP[2918:1337462] Port name: Speaker Speaker
audiounit: AudioRouteChange - reason 3
audiounit: player hardware sample rate is now at 44100.000000 Hz
audio: player started with sample format S16LE
audio: Set audio encoder: G722 16000Hz 1ch
audio: start
audiounit: record hardware sample rate is now at 16000.000000 Hz
audiounit: record: enable resampler 16000.0 -> 16000 Hz
2023-09-20 08:48:38.474122+0200 frogSIP[2918:1337767] [aid] [DetectorNode.cpp:153   rtaid::DetectorNode:0x11dfcbbb0] Caught analyzer graph exception 1718775073 !mrf slice duration must be set before configure. in /Library/Caches/com.apple.xbs/Sources/CoreAudioServices_AudioToolboxCore/CoreAudioUtility/Source/CADSP/DSPGraph/DSPGraph_Graph.cpp:686
audio: source started with sample format S16LE
audio tx pipeline:   audiounit ---> aubuf ---> vumeter ---> auconv ---> auresamp ---> frogstat ---> G722
audio rx pipeline:   audiounit <--- aubuf <--- vumeter <--- auconv <--- auresamp <--- frogstat <--- G722
video: update
Set video decoder: H264 packetization-mode=0
avcodec: h264 decoder activated

```

Config

# SIP
sip_listen		
sip_certificate	
sip_cafile		
sip_capath		
sip_transports		UDP,TCP,TLS,WS,WSS
sip_trans_def	UDP
sip_verify_server			no
sip_tos	160

# Call
call_local_timeout	120
call_max_calls		1
call_hold_other_calls	yes

# Audio
audio_path		
audio_player		audiounit,
audio_source		audiounit,
audio_alert		audiounit,
auplay_srate		16000
ausrc_srate		16000
auplay_channels		1
ausrc_channels		1
audio_txmode		poll
audio_level		no
ausrc_format		S16LE
auplay_format		S16LE
auenc_format		S16LE
audec_format		S16LE
audio_buffer		20-160		# ms
audio_buffer_mode	fixed		# fixed, adaptive
audio_silence		-35.0		# in [dB]
audio_telev_pt		101

# Video
video_source		frogcapture,Front Camera
#video_source		avformat,rtmp://127.0.0.1/app/foo
video_display		frogvideo,
video_size		"352x288"
video_bitrate		20000000
video_fps		10.00
video_fullscreen	no
videnc_format		nv12

# AVT
rtp_tos			184
rtp_video_tos		136
rtp_ports		1024-49152
rtp_bandwidth		512-4096
audio_jitter_buffer_type	fixed
audio_jitter_buffer_delay	5-10
video_jitter_buffer_type	fixed
video_jitter_buffer_delay	2-500
rtp_stats		yes
rtp_timeout		0 # in seconds

# Network
net_interface		
net_af			ipv4

**Comment by sreimers** [comment]
What version of ffmpeg is being used?

**Comment by frogblueDFi** [comment]
Tag "n6.0" from https://github.com/FFmpeg/FFmpeg.git.
Also tried with tag "n4.4.4" and branch "release/6.0". Same result.

`./configure --prefix=/<path>/baresip/iOS/build/arm64 --target-os=darwin --arch=arm64 --cc=xcrun -sdk iphoneos clang --cxx=xcrun -sdk iphoneos clang++ --enable-cross-compile --extra-cflags=-arch arm64 -Ofast -march=native -mios-version-min=13.0 -I/<path>/baresip/iOS/build/arm64/include --extra-cxxflags=-arch arm64 -Ofast -march=native -mios-version-min=13.0 -I/<path>/baresip/iOS/build/arm64/include --extra-ldflags=-arch arm64 -L/<path>/baresip/iOS/build/arm64/lib -lx264 --enable-cross-compile --enable-gpl --enable-libx264 --disable-programs --disable-doc --disable-appkit --disable-audiotoolbox --disable-sdl2 --disable-securetransport --disable-libxcb --enable-debug
`


😒

**Comment by sreimers** [comment]
Unsure if it's a ffmpeg bug. Maybe you can try to reproduce with simple ffmpeg encode example.

**Comment by frogblueDFi** [comment]
Just recognised that I also have an issue on an iPad 11th generation.
Hardware decoding is perfect, hardware encoded h264 video is of very bad quality.
It looks like a very low video.bitrate is used, but the configured values (10000000) seem to be ignored.
Video with software(!) encoding (libx264) has good quality.

Any ideas?

**Comment by frogblueDFi** [comment]
Take care: PR: https://github.com/baresip/baresip/pull/2720 
Has a memory leak!

**Comment by sreimers** [comment]
> Has a memory leak!

Can you provide more details?

**Comment by frogblueDFi** [comment]
Seems that every decoded video frame causes a memory leak.
Does not happen with original decode.c without the patch fixing frame size changes.
I am currently looking at ffdecode where an additional AVFrame (sw_frame) is allocated.
Is it correctly freed?

**Comment by sreimers** [comment]
I think I found the issue, will provide a PR.

**Comment by sreimers** [comment]
Can you try: https://github.com/baresip/baresip/pull/2752
I think I found the underlying issue for `av_hwframe_transfer_data`, it does not call av_frame_unref like `avcodec_receive_frame`.

**Comment by frogblueDFi** [comment]
Sorry I was a little bit confused with merges and PR's as I am still using v3.2.0 and patching only the decode.c file.
You added just one line, correctly?
`av_frame_unref(st->pict); /* cleanup old frame */`

Sorry, does not fix the leak.

🙁

**Comment by sreimers** [comment]
You have to ignore the old PR/Patch (is reverted now). Only 

```c
av_frame_unref(st->pict); /* cleanup old frame */
```

before `av_hwframe_transfer_data` is relevant. With Nvidia and h264_cuvid I can not reproduce a memory leak anymore.

**Comment by frogblueDFi** [comment]
Great! Frame size changes handled correctly and no more memory leaks!
macOS and iOS with VideoToolbox!
Thank you very much!
👍

**Comment by frogblueDFi** [comment]
This issues is solved in main with the line of code
`av_frame_unref(st->pict); /* cleanup old frame */`
in decode.c (module avcodec)

Thank you again
Dietmar
