### ISSUE TITLE
Module aufile does not work properly as audio source for calls

### ISSUE THREAD

**Issue by cspiel1** [baresip/baresip#2882]
### Discussed in https://github.com/baresip/baresip/discussions/2874

<div type='discussions-op-text'>

<sup>Originally posted by **joaquinjsb** January 12, 2024</sup>
Hello, 
I'm trying to make an automatic call system, but I'm struggling to play the audio only after the call has been established, I launch baresip following these steps:

1. start baresip
2. call using the /dial command
3. after the call is established manually, I just trigger the /ausrc aufile,/usr/local/share/baresip/myaudio.wav

so my question is,

1.  how can I loop the audio or start it only after the call has been answered?  when I use the /ausrc after dialing, it just likes play it instantly
2. how do I automate it? I wanted to do it via the https interface, but there's no documentation , otherwise, imma gonna do it through shell emulation but I would prefer not doing that.</div>

**Comment by cspiel1** [comment]
I could reproduce these issues with `aufile` as audio source for calls:
- When `ausrc` is set before the call, then the audio file is played too early at the peer and most of the frames are dropped. Not sure if the problem is at sender or receiver.
- When changing/restarting the stream with invoking again `/ausrc aufile,...` then the playback at the peer is not clear. Sound like underruns.

**Comment by cspiel1** [comment]
(A): The frames are dropped at the receiver because it is not enabled fast enough. This occurs only when the caller is the receiver and the callee is the sender of the audio file. The callee starts sending RTP immediately after sending the SDP answer. While the caller has to receive and process the SDP answer before it can enable the stream. That's why a few audio frames are lost.

**Comment by alfredh** [comment]
If audio frames are lost in the beginning, it might be possible to make some workarounds:

1. add a small start timer (e.g. 200ms)
2. add some silence to the beginning of the WAV file


In a call setup sequence:

```
-INVITE->
<-200 OK-
-ACK->
```

The RTP ports must be ready to receive packets *before* the INVITE is sent out.

Same thing with sending 200 OK.

The audio file should be started when receiving ACK.


Alfred

**Comment by cspiel1** [comment]
You're right. I'll try to find a work around or the ACK solution this or next week.

**Comment by Cherry2397184651** [comment]
> ### 在 #2874 中讨论
> 引用自 **joaquinjsb** 2024 年 1 月 12 日您好，我正在尝试制作自动呼叫系统，但是只有在建立呼叫后我才能播放音频，我按照以下步骤启动裸机：
> 
> 1. 开始 Baresip
> 2. 使用 /dial 命令进行呼叫
> 3. 手动建立调用后，我只需触发 /ausrc aufile，/usr/local/share/baresip/myaudio.wav
> 
> 所以我的问题是，
> 
> 1. 如何循环播放音频或仅在接听电话后才开始播放？当我在拨号后使用 /ausrc 时，它只是喜欢立即播放它
> 2. 如何实现自动化？我想通过 https 接口来做，但没有文档，否则，imma 将通过 shell 仿真来做，但我宁愿不这样做。

Hello, I am currently working as an intern in a company, and I am also trying to build an automatic call system. I would like to ask you how to achieve it.

**Comment by maximilianfridrich** [comment]
I have a fix for part A (I believe):
- https://github.com/baresip/baresip/pull/2909

**Comment by joaquinjsb** [comment]
> I have a fix for part A (I believe):
> 
> - https://github.com/baresip/baresip/pull/2909

Thanks man! I'll wait for it to be merged and I'll let you know if it's working properly, or if you guys want I can try to build this pr and check

**Comment by maximilianfridrich** [comment]
From #2909:

@joaquinjsb There are multiple ways to listen to BareSIP events - D-Bus, or TCP/UDP sockets for example. I'm not an expert on these things though.

**Comment by joaquinjsb** [comment]
I'll give a look to it, or otherwise just gonna use some long wav of 1-2 minutes.

Thanks for your valued support!

**Comment by cspiel1** [comment]
The main issue (A) is solved.
(B): Optimization should be done for `audio_txmode   thread`. We put this onto our TODO list for next release. I'll add this to https://github.com/baresip/baresip/wiki/Roadmap

**Comment by f18m** [comment]
FWIW, using latest baresip main branch, I still get the problem (A).
See logs of my attempt at https://groups.google.com/g/baresip/c/FVf0ewXXp2g/m/bnjZ5l4DBAAJ

**Comment by maximilianfridrich** [comment]
@f18m I'm not sure if what you describe in the Google group is a bug because in the log you provide we can see that BareSIP received a 183 response from the peer which establishes early media. See e.g. https://github.com/baresip/baresip/pull/2909#issuecomment-1938729568 where I explained this. It looks like your scenario might be the same - early media is established, so the streaming starts.

**Comment by f18m** [comment]
oh you're right @maximilianfridrich . I see the SIP 183 indeed. Do you think the VOIP provider in such a case would be expected to buffer the RTP stream and send it to the called party once the call goes in estabilished state?
Because I'm pretty sure this is not what's happening in my case with my VOIP provider.
Would you accept a patch to configure baresip to _ignore_ the SIP 183 / early-media option and just wait for the call to go estabilished?

**Comment by cspiel1** [comment]
No, a SIP 183 should not be ignored.

**Comment by maximilianfridrich** [comment]
> Do you think the VOIP provider in such a case would be expected to buffer the RTP stream and send it to the called party once the call goes in estabilished state?

I don't think anyone would ever do that, no. That would mess up the real time communication.

> Would you accept a patch to configure baresip to ignore the SIP 183 / early-media option and just wait for the call to go estabilished?

I'm not a maintainer, but maybe such a feature could make sense. But maybe you can first check if proper SIP signalling from the peer could also be achieved - if the peer sends a 183 which establishes an audio stream, then the audio should start playing. If early media is not wanted, then no (or a correct) 183 should be sent.

> No, a SIP 183 should not be ignored.

I don't think he meant literally ignoring it, I think he just meant the feature "start playing an audio file as audio source only when a call is established, not in early media".

**Comment by sreimers** [comment]
Isn't normaly for the duration between SIP 183 and SIP 200 a "between sound" played (local ringing tone to remote) and if accepted (200) the real audio source is connected locally?

**Comment by maximilianfridrich** [comment]
You're right @sreimers, at least for the callee side that seems like a common scenario. For the caller side I'm not so sure. I think there are "early audio" use cases in some of our setups, I would have to ask around. Further, different stream types are often handled differently, for example for a video stream, it is much more common to be immediately connected to show a "preview video" (e.g. to see who rang from a door).

I think the feature suggested by @f18m could make sense, if it is configurable.

**Comment by cspiel1** [comment]
First of all, the discussion started yesterday by @f18m is off topic here. Now I think it is not possible to extract it to a separate discussion and reference this issue.

A common early audio use-case is that
- the callee sends 183 Session Progress with `audio=sendonly` which results in
- the callee sends a calm down announcement or some music until the user/operator at the callee answers the call.

I think it is not too late to start a new discussion for a new feature and clearly separate this two different use-cases. Let's start with a SIP/SDP trace. @f18m please could you start a discussion with `baresip -s` and describe as short as possible what you would expect?

**Comment by f18m** [comment]
Hi @cspiel1 , sorry for the mixing of topics in this issue... I opened a new discussion https://github.com/baresip/baresip/discussions/3421, let's continue there.
